language: go
sudo: false
go:
- 1.11.13
- 1.12.10
- 1.13.1
before_script:
- go get github.com/golangci/golangci-lint/cmd/golangci-lint
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- golangci-lint run
- go test -v -race ./...
- go test -v -covermode=count -coverprofile=profile.cov
- $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
